package br.jus.tjms.sgpd.enumerators;

/**
 * @version 1.0
 * @created 06-nov-2015 16:31:04
 */
public enum SituacaoSolicitacaoLicenca {
	PENDENTE,
	AGUARDANDO_ATESTADO_MEDICO,
	AGUARDANDO_COORDENADORIA_SAUDE,
	AGUARDANDO_LAUDO_MEDICO,
	AGUARDANDO_PERICIA_MEDICA,
	AGUARDANDO_LAUDO_ASSISTENTE_SOCIAL,
	AGUARDANDO_GESTAO_PESSOAL,
	AGUARDANDO_COMARCA,
	AGUARDANDO_DIRETOR_GESTAO_PESSOAL,
	DEFERIDA,
	INDEFERIDA,
	CANCELADA
}