package br.jus.tjms.sgpd.enumerators;

/**
 * @version 1.0
 * @created 06-nov-2015 16:31:05
 */
public enum TipoAposentadoria {
	POR_IDADE_COMPULSORIA,
	POR_IDADE_PROPORCIONAL_TEMPO_SERVICO,
	POR_INVALIDEZ_PROVENTOS_PROPORCIONAIS,
	POR_INVALIDEZ_PROVENTOS_INTEGRAIS,
	VOLUNTARIA_TEMPO_SERVICO_PROVENTOS_INTEGRAIS,
	VOLUNTARIA_TEMPO_SERVICO_PROVENTOS_PROPORCIONAIS
}