package br.jus.tjms.sgpd.enumerators;

/**
 * @version 1.0
 * @created 06-nov-2015 16:31:07
 */
public enum TipoSolicitacaoAposentadoria {
	PROVENTOS_INTEGRAIS_COM_PARIDADE_ART_3_EC_47_2005,
	PROVENTOS_INTEGRAIS_SEM_PARIDADE_IDADE_TEMPO_CONTRIB_ART_40_1_III_A,
	PROVENTOS_INTEGRAIS_COM_PARIDADE_ART_6_7_EC_41_2003,
	PROVENTOS_PROPORCIONAIS_SEM_PARIDADE_IDADE_TEMPO_PROPORC_CONTRIBUICAO_ART_40_1_III_B,
	PROVENTOS_PROPORCIONAIS_SEM_PARIDADE_ART_2_EC_41_2003
}