package br.jus.tjms.sgpd.enumerators;

/**
 * @version 1.0
 * @created 06-nov-2015 16:31:06
 */
public enum TipoProvimento {
	EFETIVO,
	COMISSIONADO,
	VITALICIO,	
	FUNCAO_GRATIFICADA,	
	FUNCAO_NAO_GRATIFICADA,
	FUNCAO_DE_CONFIANCA,
	LEI_3219_06_POLICIAL_MILITAR,
	RESOLUCAO_412_PROCESSO_SELETIVO_CIEE,
	INSTITUTO_MIRIM,
	CONVENIO_FAZENDA_PUBLICA_ESTADUAL,
	CONVENIO_FAZENDA_PUBLICA_MUNICIPAL,
	LEI_1511,	
	LEI_2348_01,
	LEI_39,	
	LEI_1071_90,
	RESOLUCAO_560_09_SERVICO_VOLUNTARIO,
	CONVENIO_VALE_UNIVERSIDADE,
	CONVENIO_PREFEITURAS,
	CONVENIO_INSTITUICOES_DE_ENSINO,
	PROVIMENTO_369_DE_21_06_2016	
}