package br.jus.tjms.sgpd.enumerators;

/**
 * @version 1.0
 * @created 06-nov-2015 16:31:05
 */
public enum TipoAreaConhecimento {

	
	CIENCIAS_EXATAS_E_DA_TERRA,
	CIENCIAS_BIOLOGICAS,
	ENGENHARIAS,
	CIENCIAS_DA_SAUDE,
	CIENCIAS_AGRARIAS,
	CIENCIAS_SOCIAIS_APLICADAS,
	CIENCIAS_HUMANAS,
	LINGUISTICA_LETRAS_E_ARTES,
	MULTIDISCIPLINAR,
	OUTROS
	
	
}