package br.jus.tjms.sgpd.enumerators;

/**
 * @version 1.0
 * @created 06-nov-2015 16:31:05
 */
public enum TipoPagamentoItem {
	CREDITO,
	DEBITO,
	INFORMACAO,
	TOTALIZADOR,
	BASE_CALCULO,
	
	IRRF,
	BASE_CALCULO_IRRF,
	DEDUCAO_IRRF_POR_DEPENDENTE,
	DEDUCAO_IRRF_POR_APOSENTADORIA,
	QUANTIDADE_DEPENDENTES,
	
	PREVIDENCIA_REGIME_PROPRIO,
	PREVIDENCIA_REGIME_GERAL,
	FGTS,
	BASE_CALCULO_PREVIDENCIA_REGIME_PROPRIO,
	BASE_CALCULO_PREVIDENCIA_REGIME_GERAL,
	BASE_CALCULO_FGTS,
	BASE_CALCULO_PLANO_SAUDE,
	BASE_CALCULO_CONTRIBUICAO_SINDICAL,
	
	MARGEM_CONSIGNAVEL
	
	;
}