package br.jus.tjms.sgpd.enumerators;

/**
 * @version 1.0
 * @created 06-nov-2015 16:31:05
 */
public enum TipoBaseCalculo {
	MARGEM_CONSIGNAVEL,
	DECIMO_TERCEIRO,
	FERIAS,
	HORAS_EXTRAS,
	IMPOSTO_RENDA,
	PREVIDENCIA_PROPRIA,
	PREVIDENCIA_GERAL,
	FGTS,
	PLANO_SAUDE,
	CONTRIBUICAO_SINDICAL,
	OUTROS,
	CONSIGNACAO,
	CONSIGNACAO_COMPULSORIA;
}