package br.jus.tjms.sgpd.enumerators;

/**
 * @version 1.0
 * @created 06-nov-2015 16:31:06
 */
public enum TipoRubrica {
	BASE_INICIAL,
	PERCENTUAL_BASE_INICIAL,
	BASE_ATUAL,
	PERCENTUAL_BASE_ATUAL,
	FORMULA,
	VALOR_FIXO,
	VALOR_FIXO_AREA,
	VALOR_FIXO_CARGO,
	VALOR_FIXO_AREA_CARGO,
	SOMA_RUBRICAS_BASE,
	PERCENTUAL_SOMA_RUBRICAS_BASE,
	SOMA_TIPO_BASE_CALCULO,
	PERCENTUAL_SOMA_TIPO_BASE_CALCULO,
	BRUTO,
	PERCENTUAL_BRUTO,
	DESCONTOS,
	PERCENTUAL_DESCONTOS,
	LIQUIDO,
	PERCENTUAL_LIQUIDO
}