package br.jus.tjms.sgpd.enumerators;

/**
 * @version 1.0
 * @created 06-nov-2015 16:31:06
 */
public enum TipoOcorrenciaFrequenciaApuracao {
	FERIAS,
	LICENCA,
	AFASTAMENTO,
	LICENCA_PREMIO,
	CURSO_QUALIFICACAO,
	VIAGEM_A_SERVICO,
	CONGRESSO_SEMINARIO_OUTROS,
	FALTA,
	ATRASO,
	SAIDA_ANTECIPADA,
	CARGA_HORARIA_INCOMPLETA,
	SAIDA_INTERMEDIARIA,
	FERIADO,
	PONTO_FACULTATIVO_COM_REPOSICAO,
	DISPENSA,
	PONTO_FACULTATIVO_SEM_REPOSICAO,
	INFORMACAO,
	OUTRAS
}