package br.jus.tjms.sgpd.engine.to;

public enum TipoItemCalculo {
	
	RUBRICA_CARGO,
	RUBRICA_FUNCIONARIO,
	LANCAMENTO_AVULSO,
	LANCAMENTO_AGENDADO,
	LANCAMENTO_RECORRENTE,
	PARCELA_EMPRESTIMO_CONSIGNADO,
	PLANO_SAUDE_RESPONSAVEL_FINANCEIRO,
	PLANO_SAUDE_PESSOA_INCLUSA,
	CONCESSAO_AUXILIO_EDUCACAO_INFANTIL,
	CONCESSAO_ADICIONAL_QUALIFICACAO,
	CONCESSAO_ADICIONAL_INSALUBRIDADE,
	CONCESSAO_GRATIFICACAO_ENCARGOS_ESPECIAIS,
	CONCESSAO_AUXILIO_TRANSPORTE,
	DESIGNACAO_ADICIONAL_TEMPO_INTEGRAL,
	CONCESSAO_FERIAS,
	LICENCA,
	;

}
