package br.jus.tjms.sgpd.engine.to;


public enum TipoAcaoItemCalculo {
	
	PAGAR_LANCAMENTO_AVULSO,
	PAGAR_LANCAMENTO_AGENDADO,
	REGISTRAR_HISTORICO_DO_LANCAMENTO_RECORRENTE,
	PAGAR_PARCELA_EMPRESTIMO_CONSIGNADO,
	PAGAR_GRATIFICACAO_ENCARGOS_ESPECIAIS,
	LANCAR_CREDITO,
	LANCAR_DEBITO,
	LANCAR_SUBTOTAL,
	LANCAR_SUBTOTAL_CREDITO,
	LANCAR_SUBTOTAL_DEBITO,	
	LANCAR_TOTAL,	
	BEEP,
	NADA;

}
